#!/bin/bash

source env.sh
	
docker run \
	--name=$CON_HADOOP_DATANODE1_NAME \
	-p $CON_HADOOP_DATANODE1_PORT_SV_WEB \
	-p $CON_HADOOP_DATANODE1_PORT_HD_WEB \
	-v $CON_HADOOP_DATANODE1_VOL_TMP \
	-v $CON_HADOOP_DATANODE1_VOL_HD_LOGS \
	-v $CON_HADOOP_DATANODE1_VOL_HD_TEMP \
	-v $CON_HADOOP_DATANODE1_VOL_SV_LOGS \
	-e DNSDOCK_ALIAS=$CON_HADOOP_DATANODE1_DNS_NAME \
	-h $CON_HADOOP_DATANODE1_DNS_NAME \
	--dns $HOST_IP \
	-d $IMG_HADOOP --bootstrap datanode

docker run \
	--name=$CON_HADOOP_DATANODE2_NAME \
	-p $CON_HADOOP_DATANODE2_PORT_SV_WEB \
	-p $CON_HADOOP_DATANODE2_PORT_HD_WEB \
	-v $CON_HADOOP_DATANODE2_VOL_TMP \
	-v $CON_HADOOP_DATANODE2_VOL_HD_LOGS \
	-v $CON_HADOOP_DATANODE2_VOL_HD_TEMP \
	-v $CON_HADOOP_DATANODE2_VOL_SV_LOGS \
	-e DNSDOCK_ALIAS=$CON_HADOOP_DATANODE2_DNS_NAME \
	-h $CON_HADOOP_DATANODE2_DNS_NAME \
	--dns $HOST_IP \
	-d $IMG_HADOOP --bootstrap datanode
