#!/bin/bash

source env.sh
	
docker run \
	--name=$CON_FLUME_COLLECTOR_NAME \
	-p $CON_FLUME_COLLECTOR_PORT_SV_WEB \
	-p 4545:4545 \
	-v $CON_FLUME_COLLECTOR_VOL_TMP \
	-v $CON_FLUME_COLLECTOR_VOL_FL_LOGS \
	-v $CON_FLUME_COLLECTOR_VOL_SV_LOGS \
	-e DNSDOCK_ALIAS=$CON_FLUME_COLLECTOR_DNS_NAME \
	-h $CON_FLUME_COLLECTOR_DNS_NAME \
	--dns $HOST_IP \
	-d $IMG_FLUME --bootstrap collector
