#!/bin/bash

source env.sh
	
docker run \
	--name=$CON_SPARK_SLAVE1_NAME \
	-p $CON_SPARK_SLAVE1_PORT_SP_WEB \
	-p $CON_SPARK_SLAVE1_PORT_SV_WEB \
	-v $CON_SPARK_SLAVE1_VOL_SP_LOGS \
	-v $CON_SPARK_SLAVE1_VOL_SV_LOGS \
	-e DNSDOCK_ALIAS=$CON_SPARK_SLAVE1_DNS_NAME \
	-h $CON_SPARK_SLAVE1_DNS_NAME \
	--dns $HOST_IP \
	-d $IMG_SPARK --bootstrap slave

	docker run \
	--name=$CON_SPARK_SLAVE2_NAME \
	-p $CON_SPARK_SLAVE2_PORT_SP_WEB \
	-p $CON_SPARK_SLAVE2_PORT_SV_WEB \
	-v $CON_SPARK_SLAVE2_VOL_SP_LOGS \
	-v $CON_SPARK_SLAVE2_VOL_SV_LOGS \
	-e DNSDOCK_ALIAS=$CON_SPARK_SLAVE2_DNS_NAME \
	-h $CON_SPARK_SLAVE2_DNS_NAME \
	--dns $HOST_IP \
	-d $IMG_SPARK --bootstrap slave